### ISSUE TITLE
Add note about `aws configure export-credentials`

### ISSUE THREAD

**Issue by jaklan** [benkehoe/aws-export-credentials#13]
After merging and releasing https://github.com/aws/aws-cli/pull/7398, I believe `aws configure export-credentials` should be the recommended solution. It would be worth to note in the `README.md` that `aws-export-credentials` is either a legacy solution (is it?) or highlight differences between these two approaches.

**Comment by jaklan** [comment]
Actually - I already see one difference: `aws-export-credentials` doesn't generate any new credentials, just utilise what's able to find in envars / `~/.aws/credentials` / `~/.aws/cli/cache`, but `aws-export-credentials` exports new credentials each time it's executed - I believe because it takes different approach and creates a new `botocore` session each time and exports its credentials?

**Comment by benkehoe** [comment]
Oh, hm. Would we consider this a bug in the CLI's implementation?

**Comment by jaklan** [comment]
I believe it's done this way on purpose in AWS CLI, to avoid any additional side effects of running `export` command. Actually `aws-export-credentials` is the one which is more like `aws-retrieve-and-export-new-credentials` 😉

**Comment by benkehoe** [comment]
I believe the AWS CLI's implementation does refresh credentials, because it uses the normal credential resolution mechanisms of the AWS CLI (and botocore). I've added a note to the README in https://github.com/benkehoe/aws-export-credentials/commit/33a60135b2fff528aea431247faae1eff87386d9

**Comment by jaklan** [comment]
@benkehoe actually I meant sth different - that `aws-export-credentials` each time creates a new session and returns new credentials, but `aws configure export-credentials` relies on the current session and returns the same credentials.

**Comment by benkehoe** [comment]
Oh, yes, I see. If there are unexpired credentials in `~/.aws/cli/cache`, `aws configure export-credentials` can use those. But boto3 does not use that cache, so `aws-export-credentials` does not either, but it does provide a separate, optional caching mechanism.

**Comment by jaklan** [comment]
Yeah yeah, I got it, just wanted to highlight the difference, but I see I already did that on January 😄

> I believe it's done this way on purpose in AWS CLI, to avoid any additional side effects of running `export` command. Actually `aws-export-credentials` is the one which is more like `aws-retrieve-and-export-new-credentials` 😉
