### ISSUE TITLE
pipx instructions might need to be fleshed out for idiots like myself

### ISSUE THREAD

**Issue by kaihendry** [benkehoe/aws-export-credentials#4]
Didn't quite grok pipx. I assumed it would install to pwd, but I think it installed into ~/.local/bin... and it still didn't find the module.
```
pipx run aws_export_credentials
'aws_export_credentials' executable script not found in package 'aws_export_credentials'. Available executable scripts:
aws-export-credentials
```

Workaround was to use `python3 -m pip install --user aws-export-credentials`

**Comment by benbridts** [comment]
I'm not sure how helpfull it is, but this page tries to explain how pipx differs from pip (and other tools): https://pypa.github.io/pipx/comparisons/

-------

For the `executable script not found` error:

Pipx can be used in two ways:
- to install something as a cli tool
- to run the same thing as a one-off without installing it.

For the first case, after installing pipx, and making sure that ~/.local/bin is in your PATH (eg. by running `pipx ensurepath
`), you would do
```
pipx install aws-export-credentials
aws-export-credentials  # this is ~/.local/bin/aws-export-credentials
```

For the second case, you would skip the install step and run
```
pipx run aws-export-credentials
```

In both cases you use the package name (with `-`), not the directory name (with `_`).

**Comment by benkehoe** [comment]
Thanks @benbridts, apparently I overlooked this issue. I should also probably get this into homebrew.
