### ISSUE TITLE
Does it work with assume-role?

### ISSUE THREAD

**Issue by kaihendry** [benkehoe/aws-export-credentials#5]
```
aws --profile mine sts assume-role --role-arn "arn:aws:iam::XYZ:role/ViewLogsPlease" --role-session-name ViewOne
{
    "Credentials": {
        "AccessKeyId": "REDACTED",
        "SecretAccessKey": "REDACTED",
        "SessionToken": "REDACTED",
        "Expiration": "2021-08-17T09:56:17+00:00"
    },
    "AssumedRoleUser": {
        "AssumedRoleId": "AROARIZSHQ5ZB4BAEOCU2:ViewOne",
        "Arn": "arn:aws:sts::XYZ:assumed-role/ViewLogsPlease/ViewOne"
    }
}
```

Right now, [AFAICT I'm supposed to set this up manually](https://aws.amazon.com/premiumsupport/knowledge-center/iam-assume-role-cli/), maddeningly

**Comment by benkehoe** [comment]
`aws-export-credentials` doesn't do role assumption, to keep it simple (for example, there are a lot of parameters for `sts:AssumeRole`). As you're already using named profiles, you can [add a profile in your configuration to do role assumption](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html):

```ini
[ViewLogsPlease]
source_profile = mine
role_arn = arn:aws:iam::XYZ:role/ViewLogsPlease
# this is optional, a session name will be auto-generated if it's not provided
# role_session_name = ViewOne
```
and then when you use the `ViewLogsPlease` profile in the CLI or SDKs, it will automatically assume the role using the credentials from the `mine` profile, including refreshing the credentials for `ViewLogsPlease` if they expire.

If you'd like to do role assumption programmatically in Python, I've got [`aws-assume-role-lib`](https://github.com/benkehoe/aws-assume-role-lib) for that, which handles all of the complexity of role assumption.

**Comment by benkehoe** [comment]
I caved and added support for printing credentials on the command line to `aws-assume-role-lib`. See the details [here](https://github.com/benkehoe/aws-assume-role-lib#command-line-use). I feel that the split in responsibilities between these two libraries is the right one, especially since `aws-export-credentials` already supports role assumption with config profiles.

**Comment by kaihendry** [comment]
hi Ben, I'm probably being a massive idiot, though my problem is how to ingest the JSON that AWS cli emits, like after running `aws sts get-session-token --serial-number arn:aws:iam::1234567889:mfa/kai --token-code 222166 > /tmp/creds.json`

Currently I am being daft and writing shell scripts like this to apply the variables:


```
creds=/tmp/creds.json
AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId < $creds) AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey < $creds) AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken < $creds) aws lambda list-functions 
```
