### ISSUE TITLE
Forcing update

### ISSUE THREAD

**Issue by fittyCent** [benkehoe/aws-export-credentials#9]
Any way to force an update after creds are already exported to the cred files?

I have creds with expiration time and needs to be refreshed but the tool doesn't seem to do that if cred files are already present. There is a `--refresh` option but i think that may be for something else.

**Comment by benkehoe** [comment]
If you're using `--credentials-file-profile`, there's no involvement of expiration, the credentials are always written. `--refresh` is for the `--cache-file` option, which is a separate file, not the `~/.aws/credentials`.

**Comment by benkehoe** [comment]
Are you sure that the file isn't being updated? Or perhaps are the credentials being updated, but the expiration field being left alone? [The code only writes the expiration field if it knows the expiration](https://github.com/benkehoe/aws-export-credentials/blob/fc3f70895338c1e6617999a03ced94694056086b/aws_export_credentials/aws_export_credentials.py#L214), so if it doesn't have an expiration and it's writing to a section that does, that field wouldn't get updated.

**Comment by benkehoe** [comment]
Closing this as I didn't get a response
